"""Field types the app-owned definitions need beyond Django's (P06.2 Stage B1).

``SequenceField`` is a database-assigned, monotonically increasing ``bigint``: on
PostgreSQL a ``GENERATED BY DEFAULT AS IDENTITY`` column, the same column type Django
gives its own ``BigAutoField``. Django allows an identity column only as a model's
primary key (``fields.E100``); this field carries one beside the key, as an order key
that neither the app's clock nor a random value decides (the P06.2 brief, "B1's design
points", a; DM-15 3.1). The app never writes it: an insert sends the ``DEFAULT`` keyword
and reads the assigned value back through ``RETURNING``, as Django does for its own
identity primary keys. Nothing here runs SQL.
"""

from django.db import models


class DatabaseAssigned(models.Expression):
    """The ``DEFAULT`` keyword in an ``INSERT``: the database assigns the value."""

    def as_sql(self, compiler, connection):
        return "DEFAULT", []


class SequenceField(models.BigAutoField):
    """A ``bigint`` the database assigns in insertion order (an identity column), not
    the primary key. ``BigAutoField`` gives it Django's identity column type and the
    migration autodetector's rule that an identity column needs no one-off default when
    it is added to an existing table; the three overrides below take it off the primary
    key: the check that an auto field is the key, the registration as the model's auto
    field (so the UUID key stays what ``save`` treats as the key), and the deconstruction
    that would pin ``primary_key=True`` into a migration."""

    description = "A database-assigned sequence value (identity column), not the primary key"

    def _check_primary_key(self):
        return []

    def contribute_to_class(self, cls, name, **kwargs):
        models.Field.contribute_to_class(self, cls, name, **kwargs)

    def deconstruct(self):
        name, path, args, kwargs = models.Field.deconstruct(self)
        kwargs.pop("blank", None)
        return name, path, args, kwargs

    def pre_save(self, model_instance, add):
        value = getattr(model_instance, self.attname)
        if add and value is None:
            # The database assigns it; the value comes back through RETURNING.
            return DatabaseAssigned()
        return value
