import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { compile } from 'json-schema-to-typescript';
import Ajv2020 from 'ajv/dist/2020.js';
import addFormats from 'ajv-formats';
import standaloneCode from 'ajv/dist/standalone/index.js';

const root = fileURLToPath(new URL('../../../', import.meta.url));
const destination = path.join(root, 'apps/mobile/src/contracts/generated');
const check = process.argv.includes('--check');
const ajv = new Ajv2020({ allErrors: false, inlineRefs: false, strict: false, validateFormats: true, unicodeRegExp: true, code: { source: true, lines: true } });
addFormats(ajv);
const exports = {};
const typeMaps = [];
const outputs = [];
for (const [scope, file] of [['development', 'gapp-dev-v1'], ['production', 'gapp-api-v1']]) {
  const schema = JSON.parse(await readFile(path.join(root, 'packages/contracts', scope, `${file}.schema.json`), 'utf8'));
  ajv.addSchema(schema);
  for (const name of Object.keys(schema.$defs)) {
    exports[`validate${name}`] = `${schema.$id}#/$defs/${name}`;
    typeMaps.push(name);
  }
  const types = await compile(schema, scope === 'development' ? 'DevelopmentRecommendations' : 'AppResponse', {
    bannerComment: '/* Generated by packages/contracts/scripts/generate.mjs. Do not edit. */',
    unreachableDefinitions: true,
    maxItems: -1,
    style: { singleQuote: true, semi: true, printWidth: 120 },
  });
  outputs.push([`${file}.ts`, types]);
}
outputs.push(['validators.js', `/* Generated by Ajv; do not edit. */\n${standaloneCode(ajv, exports).trimEnd()}\n`]);
outputs.push(['validators.d.ts', '/* Generated validator interfaces. Errors never expose payload values. */\n' + typeMaps.map(name => `export function validate${name}(value: unknown): boolean;`).join('\n') + '\n']);
await mkdir(destination, { recursive: true });
for (const [name, text] of outputs) {
  const target = path.join(destination, name);
  if (check) {
    if (await readFile(target, 'utf8').catch(() => '') !== text) throw new Error(`Generated contract drift: ${name}. Run npm run generate in packages/contracts.`);
  } else await writeFile(target, text);
}
console.log(check ? 'Generated types and runtime validators match schemas.' : 'Generated types and runtime validators.');
